### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by yichengye310** [mtobeiyf/audio-classification#19] opened 2019-09-07 22:07 UTC
What are the classes if I use ECS-10? Is it like: 0 - dog bark, 1 -  ***, ..., etc. 

I put a dog bark.ogg from the training data into the predict folder, it outputs 13 however. What is wrong with it?

Thank you.

**Comment by dmumtaz** [comment] 2020-01-20 09:16
Did you solve the issue?

**Comment by yichengye310** [comment] 2020-01-20 20:21
@dmumtaz Nope.

**Comment by imfing** [comment] 2020-01-22 04:21
@yeyicheng @dmumtaz 
Hi guys, I'm not quite sure about the problem. The commits after 4886b995bcce182c1398076371054254d809c6f4 are mainly from others' pull requests and are not fully tested because I thought nothing could be wrong since this is a simple project.
For now, I suggest you just go to my 2017 version which is way more simpler and should work just fine https://github.com/mtobeiyf/audio-classification/tree/8493d834338f6b7434ac8e35ac8492029558cf81

I'll try to diagnose and solve the problem.

**Comment by imfing** [comment] 2020-01-22 04:54
@yeyicheng @dmumtaz 
I guess I found the reason. 
https://github.com/mtobeiyf/audio-classification/blob/7c69d45c1449a17c3f5e619dc06c10dadee54e91/cnn.py#L35

Here, the `class_count` variable **simply counts all the sub-directories and files** in the `data` directory. Therefore, with `ESC-10` dataset, you will expect it to be 14 (10 folders plus those misc README files). And in 0-based index, it will be `0, 1, 2, ..., 13`.
To solve this problem, you can simply delete those standalone files as mentioned in a previous issue comment https://github.com/mtobeiyf/audio-classification/issues/2#issuecomment-402831095
And I will modify the code to prevent such behavior happening again.

Plus, another mistake is in conversion from numeric label to onehot vector. The `label.npy` has already been 0-based. So the `-1` should be removed.
https://github.com/mtobeiyf/audio-classification/blob/7c69d45c1449a17c3f5e619dc06c10dadee54e91/cnn.py#L50

Fixed in a036ccc34fad52c62dbaa4f01b5a4d6705439a42

**Comment by dmumtaz** [comment] 2020-01-22 06:08
I tried the mentioned project:
https://github.com/mtobeiyf/audio-classification/tree/8493d834338f6b7434ac8e35ac8492029558cf81

The presence of "13" as output seems to get sorted but the 0-based index causes wrong mapping of actual class tags and predicted class tags in the output.

also, removing -1 causes the error:
line 34, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 10 is out of bounds for axis 1 with size 10

**Comment by imfing** [comment] 2020-01-22 06:17
@dmumtaz 

Please pull the latest repo. I have incrementally fixed the classes issue as I said above.

Besides, as I mentioned, what you tried is a working **old version** which you don't need to modify  and it _should_ work.

Please use **the latest version**. I have tested and the problem is gone.

**Comment by dmumtaz** [comment] 2020-01-22 07:33
Sorry to disturb you again but I have an issue.
For a file from first class ie 001 it gives the output as 0 and for a file from the last 010 class it gives the output as 9.Cant there be a simple mapping between the two to remove any discrepancy or displaying the output of the prediction as string eg dogbark, rain etc instead of the folder number?
I tried the latest code also but it doesn't solve the issue.

**Comment by imfing** [comment] 2020-01-22 13:57
See the `predict()` function in `cnn.py` and do a mapping there before printing the results.

**Closed as completed** 2020-01-22 13:57 UTC
